### ISSUE TITLE
javascript domain: unrecognized jsdoc output structure

### ISSUE THREAD

**Issue by fredbi** [readthedocs/sphinx-autoapi#126]
Using jsdoc v3.5.5 from npm package.

Produces a concluding record for JS file which is not recognized. Got warning.

```
[AutoAPI] Mapping Data
WARNING: Unknown Type: {u'files': [u'D:\\src\\js\\app.js'], u'kind': u'package', u'longname': u'package:undefined'}
WARNING: Unknown Type: {u'files': [u'D:\\src\\js\\example.js'], u'kind': u'package', u'longname': u'package:undefined'}
WARNING: Unknown Type: {u'files': [u'D:\\src\\js\\fundsdkapi.js'], u'kind': u'package', u'longname': u'package:undefined'}
[AutoAPI] Rendering Data
```

```
    {
        "kind": "package",
        "longname": "package:undefined",
        "files": [
            "D:\\src\\js\\app.js"
        ]
    }
```

Filtering it mutes the warning. I have no idea of the impact on doc, though.

In mappers/javascript.py, the following filter cleans the output.

```
for item in (i for i in data if not u'files' in i):
```

**Comment by agjohnson** [comment]
Thanks for the note on the fix! I'm guessing this is an issue with the version of jsdoc we are expecting output from? If you feel like putting together a PR for this, we should be able to support multiple versions of jsdoc output.

**Comment by fredbi** [comment]
I am not sure of the result. Filtering makes it work, but in my opinion it would be better to support a new sphinx macro for package files.
I prepare a PR with the quick fix (filter out annoying fields) since it is frustrating for new users.

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
