### ISSUE TITLE
PHP language support

### ISSUE THREAD

**Issue by romaninsh** [readthedocs/sphinx-autoapi#163]
Referencing https://github.com/markstory/sphinxcontrib-phpdomain/issues/7#issuecomment-291558860, I wonder if there are any plans to implement PHP language support.

This project can read PHPDocs producing AST, which then can be converted into JSON/YAML required for this project, however I didn't find any spec for JSON/YAML.

If there would be a way to feed a static JSON/YAML api file, I could write utility to automatically generate this file.

Please suggest what's the best way to implement PHP integration.

**Comment by AWhetter** [comment]
You will need to find or make a tool that can parse PHP and output JSON/YAML files that describes what to document. You might be able to get PHPdoc to do this. I don't know. Next you'll need to get autoapi to call this tool, read its output, and convert that into internal PythonMapperBase objects that it can understand. This will probably work very similarly to how the javascript mapper works (https://github.com/rtfd/sphinx-autoapi/blob/master/autoapi/mappers/javascript.py) which reads the json from stdout, or the .NET mapper (https://github.com/rtfd/sphinx-autoapi/blob/master/autoapi/mappers/dotnet.py) which reads the json from files. Finally you'll need to make a set of templates for the final output rst (https://github.com/rtfd/sphinx-autoapi/tree/master/autoapi/templates).

**Comment by romaninsh** [comment]
@AWhetter Yep. That's pretty much as I thought. But would be nice if the JSON/YAML would be defined - to simplify the process of creating PHP parser.

As a side note - currently the tools for documenting PHP into RST have slightly been outdated, many unchanged for few years, so this could find uses.

Here is the best described scenario currently: https://mike42.me/blog/2018-06-how-to-create-effective-php-project-documentation-with-read-the-docs

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
