### ISSUE TITLE
Add list of PythonClass bases to PythonClass

### ISSUE THREAD

**Issue by andreasfelix** [readthedocs/sphinx-autoapi#182]
Currently [`PythonClass.bases`](https://sphinx-autoapi.readthedocs.io/en/latest/reference/templates.html#autoapi.mappers.python.objects.PythonClass.bases) only contains a list of strings. It would be nice if there would be another list `bases_objects` which would include the actual `PythonClass` objects similiar to the `children` list which contains `PythonPythonMapper` objects.

This would allow to display inherited attributes/methods in the API Reference. I would like to achieve something similar to [this](https://valadoc.org/gtk+-3.0/Gtk.Grid.html), where the inherited members are listed at the bottom.

**Comment by AWhetter** [comment]
I'm going to close this in favour of #183 because that has a better approach for solving what you are trying to do.
