### ISSUE TITLE
[Feature Request] support :inherited-members: and :show-inheritance:

### ISSUE THREAD

**Issue by lukehsiao** [readthedocs/sphinx-autoapi#183]
One of the key selling points of `autoapi` is that unlike `autodoc`, it does not need to load, run, or import the project being documented. However, `autoapi` current does not support showing inheritance or inherited members (see `autoapi_options` in https://sphinx-autoapi.readthedocs.io/en/latest/reference/config.html.

To be a viable replacement for `autodocs` in our use case, we would like support for `:inherited-members:` and `:show-inheritance:`.

**Comment by timokau** [comment]
Is there any example project that uses this? I tried to enable the `:show-inheritance:` option for our project, but it seems to have no effect.

- [Here](https://gitlab.com/duelpy/duelpy/-/blob/bbadf9e748b2c326a4218a6c3254db47885a0b18/sphinx/conf.py#L57) is the `conf.py`.
- [Here](https://gitlab.com/duelpy/duelpy/-/blob/bbadf9e748b2c326a4218a6c3254db47885a0b18/duelpy/algorithms/algorithm.py#L22) is a superclass that defines the `feedback_mechanism` attribute.
- [Here](https://gitlab.com/duelpy/duelpy/-/blob/bbadf9e748b2c326a4218a6c3254db47885a0b18/duelpy/algorithms/scalable_copeland_bandits.py#L13) is a subclass that inherits that attribute.
- [Here](https://duelpy.gitlab.io/-/duelpy/-/jobs/1112481606/artifacts/doc_test/autoapi/duelpy/algorithms/algorithm/index.html#duelpy.algorithms.algorithm.Algorithm.feedback_mechanism) are the rendered docs of the attribute in the superclass.
- [Here](https://duelpy.gitlab.io/-/duelpy/-/jobs/1112481606/artifacts/doc_test/autoapi/duelpy/algorithms/scalable_copeland_bandits/index.html#duelpy.algorithms.scalable_copeland_bandits.ScalableCopelandBandits) are the rendered docs of the subclass, not including the attribute documentation.
- [Here](https://gitlab.com/duelpy/duelpy/-/jobs/1112481606) are the logs of the documentation build using `sphinx-autoapi` 1.7.0.

@AWhetter could you have a look? Am I doing something wrong?

**Comment by AWhetter** [comment]
This is a different bug. AutoAPI is currently ignoring inherited attributes. Please could you make a separate issue for the problem.

**Comment by timokau** [comment]
Thanks for the response. I have opened #272.
