### ISSUE TITLE
Unclear location for relative path in autoapi_template_dir

### ISSUE THREAD

**Issue by Tanoti** [readthedocs/sphinx-autoapi#184]
According to the documentation the ``autoapi_template_dir`` option can be set to a relative path but it does not make clear what this is relative to. The most logical place would be the sphinx config dir as that is where other modules default to but this does not appear to be the case.

Please either update the docs with more information as to where the template dir is relative to or modify the base.py mapper file to expand a relative path into an absolute path relative to the sphinx config dir.

**Comment by AWhetter** [comment]
The documentation mentions that the path is relative to where `sphinx-build is run`

> To get AutoAPI to use these templates, point the :confval:`autoapi_template_dir` configuration option to your directory. It can be absolute, or relative to where sphinx-build is run.

I don't think that's great. Making it relative to the conf.py makes more sense, so that's something we'll consider for v2.

**Comment by outdooracorn** [comment]
I just got tripped up by this too! I assumed it was relative to `conf.py` like the `autoapi_dirs` option and the rest of Sphinx. 

It would be great if this could be changed! 

In the meantime, it might be worth updating the documentation **[here](https://sphinx-autoapi.readthedocs.io/en/latest/reference/config.html#confval-autoapi_template_dir)** which **doesn't** mention that it's relative to where sphinx-build is run.

**Comment by AWhetter** [comment]
Good idea! I'll get a note added to that section as well.

**Comment by timokau** [comment]
Is there any example project that uses this? I tried to enable the `:show-inheritance:` option for our project, but it seems to have no effect.

- [Here](https://gitlab.com/duelpy/duelpy/-/blob/bbadf9e748b2c326a4218a6c3254db47885a0b18/sphinx/conf.py#L57) is the `conf.py`.
- [Here](https://gitlab.com/duelpy/duelpy/-/blob/bbadf9e748b2c326a4218a6c3254db47885a0b18/duelpy/algorithms/algorithm.py#L22) is a superclass that defines the `feedback_mechanism` attribute.
- [Here](https://gitlab.com/duelpy/duelpy/-/blob/bbadf9e748b2c326a4218a6c3254db47885a0b18/duelpy/algorithms/scalable_copeland_bandits.py#L13) is a subclass that inherits that attribute.
- [Here](https://duelpy.gitlab.io/-/duelpy/-/jobs/1112481606/artifacts/doc_test/autoapi/duelpy/algorithms/algorithm/index.html#duelpy.algorithms.algorithm.Algorithm.feedback_mechanism) are the rendered docs of the attribute in the superclass.
- [Here](https://duelpy.gitlab.io/-/duelpy/-/jobs/1112481606/artifacts/doc_test/autoapi/duelpy/algorithms/scalable_copeland_bandits/index.html#duelpy.algorithms.scalable_copeland_bandits.ScalableCopelandBandits) are the rendered docs of the subclass, not including the attribute documentation.
- [Here](https://gitlab.com/duelpy/duelpy/-/jobs/1112481606) are the logs of the documentation build using `sphinx-autoapi` 1.7.0.

@AWhetter could you have a look? Am I doing something wrong?
