### ISSUE TITLE
Tests not in pypi sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [readthedocs/sphinx-autoapi#192]
Hi! I'm packaging python-sphinx-autoapi for Arch Linux.
We usually run the test suite that a package offers. For packaging purposes it's more convenient to use the pypi source tarballs (more unique naming schemes).
Unfortunately the sdist tarball on pypi doesn't include the tests.

It would be awesome if you could add them in an upcoming release! Thanks!

**Comment by AWhetter** [comment]
Good point! Thanks for the report. I've just released a new version and it contains the tests in the sdist.
