### ISSUE TITLE
'ImportFrom' object has no attribute 'getattr'

### ISSUE THREAD

**Issue by mazlum** [readthedocs/sphinx-autoapi#193]
Hi,

I'm getting in the following error when I use "show-inheritance-diagram".

`  
/autoapi/inheritance_diagrams.py

 target = (target.getattr(path_stack.pop()) or (None,))[0]
AttributeError: 'ImportFrom' object has no attribute 'getattr'
`

**Comment by AWhetter** [comment]
Please can I see the code that its parsing? It's not clear to me how `target` has ended up being an ImportFrom node.

**Comment by mazlum** [comment]
I don't understand. I just installed autoapi and set options like this in the conf.py

`autoapi_options = [
    "members",
    "undoc-members",
    "private-members",
    "special-members",
    "show-inheritance",
    "show-inheritance-diagram",
    "show-module-summary",
    "special-members",
]`

Then I'm getting this error.  Of course I installed Graphviz. 

sphnix==3.0.2
sphinx-autoapi==1.3.0

**Comment by AWhetter** [comment]
I meant can I see the code that you are trying to generate the documentation for.

**Comment by AWhetter** [comment]
I've managed to reproduce this by having a top level package (A) import a submodule (B) and then try to generate a diagram using something in B (eg A.B.c).
So we need to get the directive to follow imports.
