### ISSUE TITLE
Issues with whitespaces/indentation in docstring

### ISSUE THREAD

**Issue by clegaard** [readthedocs/sphinx-autoapi#194]
Hi,

First of all, thank you for your work on the tool, it is a true timesaver :)

However, I am getting warnings when building the sphinx documentation for the following docstring:

```Python
def from_folder_class_data(path: AnyPath) -> Dataset:
    u"""Load data from a folder with the data structure:

    ```
    data
    ├── class1
    │   ├── sample1.jpg
    │   └── sample2.jpg
    └── class2
        └── sample3.jpg
    ```

    Arguments:
        path {AnyPath} -- path to nested folder

    Returns:
        Dataset -- A labelled dataset of data paths and corresponding class labels,
                   e.g. ('nested_folder/class1/sample1.jpg', 'class1')
    """
```

Executing *make html* generates the error message:
```Bash
...\docs\autoapi\datasetops\index.rst:465: WARNING: Unexpected indentation.
```

The generated file:
![image](https://user-images.githubusercontent.com/18687499/78701139-c9c33680-7906-11ea-9e38-70ca25a546f0.png)

(sorry I can't get GitHub to escape the ```)

The indentation before *sample3.jpg* seems to be the culprit, replacing it with, say *** removes the warning.
Also, the presence of the code fence (```) does not appear to be the cause of the issue.

Is this a bug or am I simply providing an invalid docstring?

**Comment by AWhetter** [comment]
This is an invalid docstring. I think you're trying to use Google format? That would look like this:

```
def from_folder_class_data(path: AnyPath) -> Dataset:
    u"""Load data from a folder with the data structure:

    ```
    data
    ├── class1
    │   ├── sample1.jpg
    │   └── sample2.jpg
    └── class2
        └── sample3.jpg
    ```

    Arguments:
        path (AnyPath): path to nested folder

    Returns:
        Dataset: A labelled dataset of data paths and corresponding class labels,
                   e.g. ('nested_folder/class1/sample1.jpg', 'class1')
    """
```

I would say it's unusual to include types in your docstring because you have type hint. Google format will allow you to omit the types.
Does that make sense?

**Comment by clegaard** [comment]
I am using a plugin [autoDocstring](https://github.com/NilsJPWerner/autoDocstring) for vscode, which I believe is set to use docBlockr by default. I agree with you that the combination of type hints and explicitly stating it in the docstring seems redundant :)

I ended up wrapping the tree structure listing in a .. code-block:: directive which resolves the issue.
I am still curious in regard to how whitespace should be represented in a situation like a file tree structure?

**Comment by AWhetter** [comment]
Oh I see. I misunderstood the problem. That's what I get for bug triaging so late ;)
I don't know of a way to escape indentation like that. I would do what you've done and put it in a code block as well.
