### ISSUE TITLE
Go bug: Could not import extension sphinxcontrib_golangdomain

### ISSUE THREAD

**Issue by jwflory** [readthedocs/sphinx-autoapi#196]
# Summary

`sphinxcontrib_golangdomain` is not found as an extension when added to `conf.py` even when installed

# Background

I followed the instructions in the [Go tutorial](https://sphinx-autoapi.readthedocs.io/en/latest/tutorials.html#go), but when I go to build my docs with `sphinx-build`, this is the output:

```sh
Running Sphinx v3.0.1

Extension error:
Could not import extension sphinxcontrib_golangdomain \
    (exception: No module named 'sphinxcontrib_golangdomain')
```

I tested this with Sphinx 2.4.4 and 3.0.1 and got the same result.

# Details

Somehow Sphinx is not finding the extension, even though it is in my `conf.py` file:

```python
extensions = [
    'autoapi.extension',
    'recommonmark',
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.imgmath',
    'sphinx.ext.viewcode',
    'sphinxcontrib_golangdomain',
]
```

Not sure if there is more helpful debug output I can provide, but let me know what to do if more verbosity is needed somewhere.

# Outcome

Blocks using Sphinx-AutoAPI for Go code

**Comment by AWhetter** [comment]
The golangdomain extension doesn't support Sphinx 3. Sphinx 2 works.
I haven't pursued getting the golangdomain extension updated but they would probably accept a patch?

**Comment by jwflory** [comment]
> I tested this with Sphinx 2.4.4 and 3.0.1 and got the same result.

Hi @AWhetter, it still doesn't work for me with Sphinx 2.
