### ISSUE TITLE
Custom Jinja2 filters

### ISSUE THREAD

**Issue by Markus-Goetz** [readthedocs/sphinx-autoapi#200]
In issue #160 @AWhetter mentions that it is possible to introduce custom Jinja2 filters to sphinx-autoapi via the conf.py. I am not quite sure how this is supposed to happen. While Sphinx will execfile() the conf.py, the Jinja2 environment spawned there, would be different from the one created in mappers/base.py.

Hence, I am not seeing a way to provide sphinx-autoapi with custom filters. Would you mind explaining how this can be achieved?

Edit: I could imagine this feature could also be provided by a execfile() on a Python source code file, defined in the conf.py, where the Jinja2 object is passed into. A user can then arbitrarily customize the Jinja2 instance.

**Comment by AWhetter** [comment]
This currently isn't possible. It's still something that I think would be useful. I envisioned it as working by adding a new option in conf.py that would take a list of Jinja filters (and tests and globals) defined in the conf.py and that eventually get passed into the jinja environment [here](https://github.com/readthedocs/sphinx-autoapi/blob/428e8526f0ec3abfbed4f254b70a76c0e20caf47/autoapi/mappers/base.py#L180).
