### ISSUE TITLE
Availability of `member-order` options

### ISSUE THREAD

**Issue by gugarosa** [readthedocs/sphinx-autoapi#201]
Hello! Hope everything is all right!

I was wondering if sphinx-autoapi has any support for `member-order` configurations? I have been using it for a while but could not find anywhere how to order my docs by source; it always uses an alphabetical order.

Best regards,
Gustavo.

**Comment by mesca** [comment]
Also interested by source order.

**Comment by AWhetter** [comment]
Thanks for the suggestion. I've added an autoapi_member_order option to configure this behaviour.
