### ISSUE TITLE
link to github source w/ line number?

### ISSUE THREAD

**Issue by dzheng256** [readthedocs/sphinx-autoapi#202]
Is it possible to use https://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html to generate a github link including the specific line numbers for each function? Currently I've got it working more or less, but every function links to the github page for that module's source. I'm wondering if it is possible to have autoapi figure out the corresponding line in the file so I can include that in the github link.

Essentially in 
```
def linkcode_resolve(domain, info):
    if domain != 'py':
        return None
    if not info['module']:
        return None
    filename = info['module'].replace('.', '/')
    return "https://somesite/sourcerepo/%s.py" % filename
```
which is the example from the above link, I guess `info` would have to include the line numbering 

 Thanks!

**Comment by AWhetter** [comment]
The viewcode support has to do something similar. You should be able to adapt what it does to work for the linkcode extension: https://github.com/readthedocs/sphinx-autoapi/blob/b52378fa51e7bccd9093987c66e233244d4ec045/autoapi/extension.py#L245-L249
What it does isn't exactly part of the public API of AutoAPI but it'll do what you want.
Let me know how you get on.

**Comment by aaugustin** [comment]
In case that helps, I implemented a version this here:

https://github.com/aaugustin/websockets/blob/main/docs/conf.py#L61-L105

This implementation supports functions, classes, and methods, which is all I care about here.

**Comment by kddubey** [comment]
@aaugustin's solution worked great! I just had to add that the object should be unwrapped, which I learned from sklearn [here](https://github.com/scikit-learn/scikit-learn/blob/main/doc/sphinxext/github_link.py#L46-L48).

Add

```python
obj = inspect.unwrap(obj)
```

[right before](https://github.com/aaugustin/websockets/blob/778a1ca6936ac67e7a3fe1bbe585db2eafeaa515/docs/conf.py#L121) getting the object's sourcefile
