### ISSUE TITLE
Inherit parent class docstrings

### ISSUE THREAD

**Issue by mesca** [readthedocs/sphinx-autoapi#203]
I was wondering if there is a way to use the docstring of the parent class method when the same method in the child class has no docstring. This is the default behavior in autodoc, and a feature I am really missing in autoapi.

**Comment by AWhetter** [comment]
Thanks for the suggestion. Classes and methods now inherit docstrings from their parent, behaving like they would in live Python.

**Comment by mesca** [comment]
Great, thanks!
