### ISSUE TITLE
ignore things that are re-exported via __init__.py?

### ISSUE THREAD

**Issue by dzheng256** [readthedocs/sphinx-autoapi#204]
If I have, for example
`b/module.py` and `a/__init__.py` which does `from b.module import BClass`, then in the docs autoapi generates there is also `a.BClass`. How can I prevent this re-export from getting picked up? This behavior seems a bit odd to me, though I suppose it may be intentional. However I don't want to have this in my docs, and I haven't found a way to fix it via a config option.

**Comment by AWhetter** [comment]
The members are included because AutoAPI aims to document anything that is accessible through the actual module when loaded in Python, which includes anything that has been imported.
However I've added an `imported-members` value to `autoapi_options` that you can remove to disable this behaviour.

**Comment by dzheng256** [comment]
thanks @AWhetter, when a new release of `autoapi` containing this feature be published?
