### ISSUE TITLE
SWIG / Python module not found 

### ISSUE THREAD

**Issue by razvnane** [readthedocs/sphinx-autoapi#206]
I am using sphinx-autoapi to document a SWIG module, and everything works fine locally, however on RTD the APIs are not generated because of a warning: 

> WARNING: autodoc: failed to import class 'openql.CReg' from module 'openql'; the following exception was raised:
No module named 'openql'

I am not sure whether this is a problem with how I set the paths for RTD, or that this is not possible/a bug for how a SWIG modules are searched on RTD (locally, the html builder generates the API documentation). 

Folder structure:

>- docs/
    |--- conf.py
>- swig/
    |--- openql.i // File where the API doc resides
    |--- openql/  \_\_init\_\_.py

Paths added in conf.py:

> sys.path.insert(0, os.path.abspath('../swig/openql'))
> autoapi_dirs = ['../swig/openql']

**Comment by jwflory** [comment]
Might be a duplicate of #189?

**Comment by razvnane** [comment]
No, it is not because I am trying to generate the documentation from a source SWIG file (openql.i) instead of __init__.py, which is one level lower. But I realized that I might be doing things the wrong way so I am closing this issue.
