### ISSUE TITLE
Imported classes within module cause WARNING: xxx specified for inheritance diagram is not a class or module

### ISSUE THREAD

**Issue by NichtJens** [readthedocs/sphinx-autoapi#208]
I am having a problem in a larger project, but tried to condense it to a minimal example:

With the following setup

```
.
└── lib
    ├── __init__.py
    └── something.py
```

`__init__.py`:

> ```Python
> from .something import Something
> ```
> 

`something.py`:

> ```Python
> class Base:
>     pass
> 
> class Something(Base):
>     pass
> ```

I am getting
> WARNING: lib.Something specified for inheritance diagram is not a class or module

Importing the class to one level above has the goal to condense the user-facing parts to a more concise API, this is currently a bit subverted since the imported classes are then not fully documented, only the originals are. And the warning is a bit misleading...

**Comment by AWhetter** [comment]
Having a look at the code, the directive isn't looking for imported classes, only strict definitions:
https://github.com/readthedocs/sphinx-autoapi/blob/efe815c1df16a616b40b44cb679fda4a4eb7895a/autoapi/inheritance_diagrams.py#L39-L47

We should be able to get it to follow imports as well.

**Comment by NichtJens** [comment]
Perfect! Thank you :)
