### ISSUE TITLE
New pip release?

### ISSUE THREAD

**Issue by MatthijsBurgh** [readthedocs/sphinx-autoapi#210]
Could you provide a new pip release?

**Comment by dzheng256** [comment]
+1, I would also appreciate a new release w/ so we can have the fix for https://github.com/readthedocs/sphinx-autoapi/issues/204!

**Comment by AWhetter** [comment]
Apologies for the slowness. It's incoming but I'm trying to get a fix in for #193 before the next release. If it takes much longer then I'll just release as-in and the #193 fix can go in a separate release.

**Comment by AWhetter** [comment]
v1.4.0 is out
