### ISSUE TITLE
sphinx.ext.viewcode not working ? 

### ISSUE THREAD

**Issue by Cdebus** [readthedocs/sphinx-autoapi#212]
For our project documentation we would like to show [Source] links next to the API references. In principle ```sphinx.ext.viewcode``` should be able to provide this, however it doesn't seem to be working so far neither on my local build nor on the readthedocs build. From the references to ```sphinx.ext.viewcode``` I have found so far, none is using sphinx-autoapi, they all rely on autodoc (e.g. https://github.com/readthedocs/readthedocs.org/issues/2139).

Anyone with some experience on this topic?

**Comment by AWhetter** [comment]
Hi @Cdebus. If this isn't a problem with AutoAPI then https://github.com/readthedocs/readthedocs.org/issues seems like the right place to raise the issue rather than here.

**Comment by markusritschel** [comment]
Just because I stumbled upon the same problem. The solution that worked for me is mentioned [here](https://stackoverflow.com/a/51312475/5925453)
and is basically that `'sphinx_autodoc_typehints'` needs to be added **after** `'sphinx.ext.napoleon'`.
