### ISSUE TITLE
Change title of the root index

### ISSUE THREAD

**Issue by mjedmonds** [readthedocs/sphinx-autoapi#216]
Is is possible to rename the template or use a user template for the root index of the generated RST? The template is located at: 
[autoapi/templates/index.rst](https://github.com/readthedocs/sphinx-autoapi/blob/master/autoapi/templates/index.rst), but I don't see an option to change this title.

I have a project with C++ and Python APIs, and I would like to name the headers of each sub API appropriately. For instance, I want to name the `sphinx-autoapi` generated API header to be `Python API Reference`. I'm also using [Exhale](https://exhale.readthedocs.io/en/latest/) for the C++ API, which allows specifying a title through the `rootFileTitle` argument.

Apologies if there's a simple answer to this - I was not able to find anything.

**Comment by AWhetter** [comment]
The documentation describes how to do this here: https://sphinx-autoapi.readthedocs.io/en/latest/how_to.html#how-to-customise-the-index-page

So you'll need a directory like

```
_autoapi_templates
└── index.rst
```

and you point AutoAPI to it with `autoapi_template_dir = '_autoapi_templates'` in your `conf.py`.
