### ISSUE TITLE
Is this extension `parallel_read_safe=True`?

### ISSUE THREAD

**Issue by humitos** [readthedocs/sphinx-autoapi#222]
This extension does not return metada on the `autoapi.extension.setup` function. By default, Sphinx marks `parallel_read_safe=False` and `parallel_write_safe=True`.

So, when running Sphinx with `-j auto`, if this extension is installed in the project, it will always run in serial:

```
WARNING: the autoapi.extension extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```

It would be good if we can find out if this extension is parallel safe or not and define it explicitly.

Reference: http://www.sphinx-doc.org/en/stable/extdev/#extension-metadata

**Comment by CMeza99** [comment]
issue is not resolved:
```
sphinx.errors.SphinxParallelError: TypeError: cannot pickle 'module' object

Sphinx parallel build error:
TypeError: cannot pickle 'module' object
```
```
❯ sphinx-build --version
sphinx-build 3.2.0
```
sphinx-autoapi was grabbed from the master branch.

**Comment by renefritze** [comment]
`parallel_read_safe` changed back to `False` in 0667de40376fc16c3c17febf28951527cbaaff8a, so I'm guessing there is an actual problem with parallel read @AWhetter ?

**Comment by AWhetter** [comment]
Yes but I'm not sure what the problem is.
