### ISSUE TITLE
fix for issue #193?

### ISSUE THREAD

**Issue by dzheng256** [readthedocs/sphinx-autoapi#223]
I saw that there are plans to fix https://github.com/readthedocs/sphinx-autoapi/issues/193, but from https://github.com/readthedocs/sphinx-autoapi/issues/210 it is unclear if the fix for 193 made it into the latest pip release. I am running into the `'ImportFrom' object has no attribute 'getattr'` issue, so just wanted to check on the status of the fix. Thanks!

**Comment by AWhetter** [comment]
As outlined in the changelog (https://github.com/readthedocs/sphinx-autoapi/blob/master/CHANGELOG.rst) this is supposed to be fixed in v1.4.0.

**Comment by AWhetter** [comment]
I'm going to close this under the assumption that it was a question but let me know if this is still an issue for you.
