### ISSUE TITLE
Allow the choice of classes having their own page

### ISSUE THREAD

**Issue by AWhetter** [readthedocs/sphinx-autoapi#226]
In a project that contains few functions and many classes with a lot of methods, it might be desirable to be able to have classes create rst files rather than modules or in addition to modules. An example of such documentation would be the PySide documentation.
We need to add a new option to support this behaviour. I think it's fine for it to be specific to having Python classes in particular produce new pages, rather than it being a list where you define which type of objects you want to create new pages. I can't think of a use case where you would want a single function or a single module level attribute per page. Module pages can already by turned off by skipping them with the autoapi-skip-member event.
It's likely that the templates would need to change to make this behaviour make sense, but it's fine for us to only add the option and expect the user to customise their own templates.

**Comment by astrojuanlu** [comment]
I came here to report this issue.

This is the behavior of `sphinx.ext.autosummary`, and therefore for people migrating from it, it would be nice to have an option to carry the same behavior to `sphinx-autoapi`. Otherwise, migrating necessarily implies breaking all the URLs, which is far from ideal.

This is the part of the `module.rst` template that renders the objects themselves:

https://github.com/readthedocs/sphinx-autoapi/blob/85739d513e2dceba4e9c9190aead68b7d9f96870/autoapi/templates/python/module.rst?plain=1#L110-L112

**Comment by raphaelquast** [comment]
Hey, I just ended up here after hours of trying to get unique files for each object of a module...
(using sphinx-autosummary with this templates: https://stackoverflow.com/a/62613202/9703451)

Is there already an existing workaround that can be used to tell sphinx-autoapi to create unique files for each 
object of a module? (e.g. can this even be done with a nicely configured template or would this require actual changes in sphinx-autoapi)

In my opinion, having a unique page for each object would make the docs much less overwhelming...

**Comment by jorgepiloto** [comment]
After taking a look to the source code, it looks like this is the method in charge of creating the doc source files prior Sphinx rendering:

https://github.com/readthedocs/sphinx-autoapi/blob/92437c9af72b75fbccb451da95f85dbbf0c3f0da/autoapi/mappers/base.py#L310-L329

Maybe, we could add a second loop if enabled through autoapi configuration to generate files for each module object:

```python
# conf.py
autoapi_render_in_single_page = ["class", "function"]
```

As said before, any guidance is more than welcome, Ashley 👍🏼

**Comment by AWhetter** [comment]
Closing as implemented.
