### ISSUE TITLE
go documentation gives warning :  Unknown directive type "go:method".

### ISSUE THREAD

**Issue by DerThorsten** [readthedocs/sphinx-autoapi#229]
The go documentation seems to **not** find to go:method directive
: WARNING: Unknown directive type "go:method".

**Comment by DerThorsten** [comment]
a manual reinstallation of the package with the [go] option did the trick

**Comment by AWhetter** [comment]
Do you have "sphinxcontrib-golangdomain" installed? AutoAPI needs to be installed as "sphinx-autoapi[go]" to support go.
