### ISSUE TITLE
sphinx.ext.viewcode extension doesn't work when making singlehtml

### ISSUE THREAD

**Issue by tyuanhang** [readthedocs/sphinx-autoapi#238]

**Comment by AWhetter** [comment]
Please could you give some more information on the problem. What version of sphinx and autoapi are you using? Does it give you a traceback?
Do you see the problem without autoapi loaded? This might be easier to do by turning `autoapi_keep_files` on, building, and then removing autoapi.
Do you have a small test case that we can reproduce the issue with?
