### ISSUE TITLE
Support additional options to .NET constructors from domain changes

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/sphinx-autoapi#24]
The domain was updated to handle and display extra options on objects:
- `:protected:`
- `:public:`
- `:static:`

As well as property options:
- `:getter:`
- `:setter:`

And field options:
- `:adder:`
- `:remover:`

Add support for yaml fields to affect object options above and output in templates.

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
