### ISSUE TITLE
Output API info in yaml / json? and/or remove sphinx dependency?

### ISSUE THREAD

**Issue by tony** [readthedocs/sphinx-autoapi#241]
Hi there! Thank you for the project!

Is there any ambition / openness of generating output of API even without sphinx? e.g. a YAML / JSON output of a the project's tree? 

It'd be nice to have quality API data for use in _any_ project. I'd love to have API information in YAML/JSON/etc. to put into gatsby (if there was a JSON output of the project's structure, I could do the rest from there, e.g. consume it as a gatsby source)

Could be flexibility to generate a language agnostic, structured, serialized api structure to consume?

Do you know of any similar libraries that does what autoapi does, e.g. generates Python documentation, but usable in other languages (e.g. node?)

Thank you!  Feel free to close this as its more of a general question! (Sorry for any interruption!)

**Comment by AWhetter** [comment]
If there were enough of an interest in making that happen I would consider it. But I would split out the JSON generation part into it's own library and have AutoAPI consume it.
Honestly I've been thinking of going in the opposite direction and having AutoAPI not produce JSON at all. It adds an unnecessary restriction on the API parsing, and not having access to astroid directly makes some parts of it more challenging. However I will bare the questions in this issue in mind in the future.

I don't know of any similar libraries.
