### ISSUE TITLE
Silence warning about unresolved import

### ISSUE THREAD

**Issue by jakobandersen** [readthedocs/sphinx-autoapi#242]
In my project have a Python module which internally imports a module compiled from C++. This internal module is not available when the documentation is compiled and I thus get a warning (``Cannot resolve import of unknown module ... in ....``).
Is there a way to silence this warning? Otherwise it would be nice to have a config variable which can be set to a list of modules to ignore import problems from.

**Comment by AWhetter** [comment]
The way to silence this warning would be to provide a .pyi stub file that represents what's in the compiled module, so that AutoAPI can read it and understand the module itself.

**Comment by jakobandersen** [comment]
Ah, good idea. Thanks!
