### ISSUE TITLE
__init__.pyi handling

### ISSUE THREAD

**Issue by Vanuan** [readthedocs/sphinx-autoapi#243]
I find something strange about the `__init__.pyi` handling. When `__init__.py` is present and empty, the module is defined, but the classes defined in `__init__.pyi` get ignored. When `__init__.py` is missing, the classes defined is `__init__.pyi` are present but somehow end up in the `__init__` module.

What's the correct way to define `__init__.pyi` modules/packages?

**Comment by Vanuan** [comment]
As a workaround, I'm using this script which renames *.pyi to *.py:

```
for f in stubs/**/*.pyi; do
    mkdir -p py_`dirname $f` && cp -- "$f" "py_${f%.pyi}.py"
done
```

**Comment by AWhetter** [comment]
I've made a change such that the order of `autoapi_file_patterns` specifies the order of preference for reading files. So if you want AutoAPI to prefer `pyi` files over `py` then you should set `autoapi_file_patterns = ["*.pyi", "*.py"]`.
