### ISSUE TITLE
WARNING: py:class reference target not found: <ref>

### ISSUE THREAD

**Issue by amin-nejad** [readthedocs/sphinx-autoapi#257]
Hi, I have just started using sphinx and this excellent library which seems to do exactly what I want. The documentation for my python project builds properly when I run it and I can view everything as expected in the browser but the build for some reason produces hundreds of warnings, seemingly for every single reference in the arguments for functions and classes. I think this is why none of the arguments for classes and functions in the documentation website are clickable to take you to their own section - because the reference can't be resolved.

![Screenshot from 2020-11-27 13-44-19](https://user-images.githubusercontent.com/44096034/100456016-9876c100-30b7-11eb-852b-af54bb5b461c.png)

I presume I must be making some kind of stupid mistake in my `conf.py`. 

```python
"""Configuration file for the Sphinx documentation builder."""

project = "bitfount-ml"
copyright = "2020, Bitfount"
author = "Bitfount"
version = "1.0.0"
extensions = ["m2r2", "autoapi.extension"]
source_suffix = [".rst", ".md"]
templates_path = ["_templates"]

autoapi_type = "python"
autoapi_dirs = ["../../bitfountml", "../../bitfounthub"]
autoapi_member_order = "groupwise"
autoapi_keep_files = True

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
```

Any help would be appreciated - thanks!

**Comment by AWhetter** [comment]
Please could you give a more complete example of the docs that are raising a warning. Is there a repo that I can look at?
Do `DataSource`, `Schema`, and `Path` come from your repo or are they something external? You might need to use the syntax described here: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing-syntax

For the `np.ndarray` type, take a look at how to configure intersphinx: https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html In particular, you'll need to add a new entry to the mapping `'numpy': ('http://docs.scipy.org/doc/numpy/', None),`, and then you'll need to refer to `np.ndarray` as `numpy.ndarray`.

**Comment by amin-nejad** [comment]
Thanks so much for getting back to me - your response was very helpful. Unfortunately the repo is private and doesn't belong to me but I think I have fixed my problems. It turns out I had a couple of different problems and was also conflating them with one another.

So the sheer number of warnings was because I was accidentally including the `-n` flag which was running the build in nit-picky mode. Removing this flag brought down the warnings to 8 instead of 643.

I don't think this had anything to do with links to other classes in my project not displaying. I believe the cause of this was that my docstrings were in google format but I had not added `sphinx.ext.napoleon` as an extension. Doing this started to display the links (as well as fix the formatting). 

The intersphinx tip was also very helpful for linking to other libraries.

In the interests of anyone who may come across this, the current state of my `conf.py` is as follows and everything is working as expected:

```python
project = "bitfount-ml"
copyright = "2020, Bitfount"
author = "Bitfount"
version = "1.0.0"
extensions = [
    "m2r2",
    "autoapi.extension",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
]
source_suffix = [".rst", ".md"]
templates_path = ["_templates"]

autoapi_type = "python"
autoapi_dirs = ["../../bitfountml", "../../bitfounthub"]
autoapi_member_order = "groupwise"
autoapi_keep_files = True

html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "pandas": ("https://pandas.pydata.org/docs/", None),
    "pathlib": ("https://docs.python.org/3", None),
}
```
