### ISSUE TITLE
typehint not working

### ISSUE THREAD

**Issue by pangan** [readthedocs/sphinx-autoapi#258]
These sets are in config.py :
```
extensions = ['sphinx.ext.autodoc', 'autoapi.extension']
autodoc_typehints = 'description'
```

but it does not show any type hint for the methods.

if I make a manual rst file with `automodule` directive to that module, it has type hint, but the files generated by autoapi does not have any autohint!

**Comment by AWhetter** [comment]
Are you using the master branch? This feature has not been released yet.

**Comment by AWhetter** [comment]
This feature has been released so please submit a new issue if this is still a problem.
