### ISSUE TITLE
Types parameters are not fully qualified when there is more than one type parameter

### ISSUE THREAD

**Issue by joelberkeley** [readthedocs/sphinx-autoapi#265]
For types with more than one type parameter, such as `typing.Tuple`, `typing.Union` or custom types
```
class Foo(Generic[T, U]): pass
```
arguments and return value types aren't fully qualified for the type parameters. For example, in
```
def bar(x: Foo[A, B], y: A) -> Foo[C, D]:
    ...
```
A, B, C and D aren't being expanded in `Foo[...]` but are being expanded and linked when on their own, such as in `y: A`. Note: for builtins/locals, links are being made, e.g. in `Mapping[str, A]`, `str` is being linked

versions
sphinx-autoapi 0.17.0
pydata-sphinx-theme 0.4.3
Sphinx 3.4.3

**Comment by AWhetter** [comment]
I've done what I can to resolve this issue in AutoAPI alone, but there's an issue in Sphinx that prevents this from working properly. I have submitted a follow up issue upstream: https://github.com/sphinx-doc/sphinx/issues/9020
