### ISSUE TITLE
Building one page per function in the doc

### ISSUE THREAD

**Issue by Cgadal** [readthedocs/sphinx-autoapi#270]
I successfully managed to build a documentation using `sphinx-autoapi`. Currently, the tree of the API Reference goes up to the last modules, and then displays one page per module with all the functions inside. 

Is there anyway to have one page per function (and maybe then modifying the API Reference tree accordingly) ?

**Comment by AWhetter** [comment]
This currently isn't possible. But there's plans for making it happen. #226 covers this.
