### ISSUE TITLE
Modifying template to have shorter function names

### ISSUE THREAD

**Issue by Cgadal** [readthedocs/sphinx-autoapi#271]
Currently, the documentation built using `sphinx-autoapi` renders functions names in the doc as `projet.folder1.folder2.folder3.module.func_name`.

How can I modify the .rst files of the template to only display the function name ?

I understand it probably has something to do with the `obj.short_name` in the `function.rst` files of the template, but this is as far as I can go for now ...

**Comment by AWhetter** [comment]
I think you want `add_module_names` to be `False`: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-add_module_names
