### ISSUE TITLE
autoapi + napoleon + Google Styled docstrings not working

### ISSUE THREAD

**Issue by tobiwankenobii** [readthedocs/sphinx-autoapi#274]
Using autoapi for docs generating, but it seems not to work.
Docstrings like:
```
def xyz(self) -> Dict[str, bool]:
    """Xxx.

    Yyy.

    Returns:
        dict: Zzz

        example:
            {
                'x': True,
                'y': False
            }
    """
```
are causing:
![Screenshot from 2021-03-23 13-23-36](https://user-images.githubusercontent.com/49806746/112145793-1cab0200-8bdb-11eb-93e2-81e6d2586f9a.png)
in several places.

Same for:
```
"""Xyz.

Description:
    x: xxx.
    y: yyy.
    z: zzz.
"""
```

![Screenshot from 2021-03-23 13-31-21](https://user-images.githubusercontent.com/49806746/112146659-1ff2bd80-8bdc-11eb-8d56-38523699b0a7.png)

Am i doing something wrong?

**Comment by AWhetter** [comment]
In your first example, you will need to put the dictionary into a code block. An example is given here: https://www.sphinx-doc.org/en/master/usage/extensions/example_google.html?highlight=module_level_function

For your second example, "Description" is not a valid section name. The sections supported by napoleon are documented here: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html?highlight=napoleon#docstring-sections
