### ISSUE TITLE
way to include module docstrings in API TOC?

### ISSUE THREAD

**Issue by odoublewen** [readthedocs/sphinx-autoapi#276]
We like to include a short docstring for every python module in our projects.  (I.e., a docstring at the top of every `.py` file, including `__init__.py`) 

These show up in the nicely formatted module page, and I guess it's coming from these lines of the [`module.rst` template](https://github.com/readthedocs/sphinx-autoapi/blob/master/autoapi/templates/python/module.rst):

```
.. py:module:: {{ obj.name }}

{% if obj.docstring %}
.. autoapi-nested-parse::

   {{ obj.docstring|prepare_docstring|indent(3) }}

{% endif %}
```

I'd love to get these short docstrings into the autogenerated API TOC, which I guess is defined in `index.rst` template:

```
.. toctree::
   :titlesonly:

   {% for page in pages %}
   {% if page.top_level_object and page.display %}
   {{ page.include_path }}
   {% endif %}
   {% endfor %}
```

I've tried overriding this template to include my short docstrings, but to no avail. 

What is the relationship between the `page` and the `obj`?  Would it be easy to get the behavior I am describing?

Many thanks in advance, and also kudos for a very useful sphinx extension!

**Comment by AWhetter** [comment]
Unfortunately the toctree directive does not support this behaviour. You would need to request this feature to be added to Sphinx first.
