### ISSUE TITLE
More detailed contents in sidebar

### ISSUE THREAD

**Issue by sammorley-short** [readthedocs/sphinx-autoapi#282]
(Maybe this is possible and I've just missed it, so apologies in advance if that's the case)

Currently, running the extension adds just a single, childless entry to the sidebar menu. When you click this it reveals a beautiful tree hierarchy of the package's contents, which is very easy to navigate. However, once you click on one of those, the ability to navigate without returning to the root page is lost.

It would be great if there was an option to allow the sidebar to render this structure in a collapsible way, similarly to how this is done for other, as depicted below:

<img width="291" alt="Screenshot 2021-04-07 at 23 24 33" src="https://user-images.githubusercontent.com/20857520/113978146-707f3300-97f8-11eb-99fd-4670dc560152.png">

**Comment by AWhetter** [comment]
I can't reproduce the behaviour that you're describing. Do you have a small test case that shows the problem and maybe an image/gif of the sidebar?

**Comment by pork-you-pine** [comment]
If this is still relevant. I ran into this issue because I did not explicitly add the autoapi index file into my toctree.
Try adding something like this in your index.rst.
```.. toctree::
   :maxdepth: 4
   :caption: `Contents:`

   autoapi/index.rst

**Comment by sammorley-short** [comment]
Closing as I can no longer reproduce the bug.
