### ISSUE TITLE
Mangled section order by add_domain_to_toctree

### ISSUE THREAD

**Issue by jakobandersen** [readthedocs/sphinx-autoapi#283]
The automatic toctree entries from domain directives is usually nice, but I encountered an odd case. Consider
```rst
Big Header
##########

.. py:class:: MyClass

Sub-header
==========

.. py:function:: doStuff()
```
then I get
![autoapi](https://user-images.githubusercontent.com/6465735/115037986-5d8ef180-9ecf-11eb-8ccc-b09e68e55c4a.png)
The structure I would expect is
- Big Header
  -  MyClass
  - Sub-header
    - doStuff

Minimal working example: [autoapiTest.tar.gz](https://github.com/readthedocs/sphinx-autoapi/files/6325738/autoapiTest.tar.gz)

**Comment by AWhetter** [comment]
Really we should restrict the addition of toctree nodes to only where the documentation is generated.
But the fact that it edits the toctree in this way is also an issue.

This functionality exists to overcome what I see as a shortcoming of Sphinx, and ideally Sphinx would be capable of adding domain nodes to the toctree itself. I've started work on this in https://github.com/sphinx-doc/sphinx/issues/6316, but it might take a while.

**Comment by jakobandersen** [comment]
> This functionality exists to overcome what I see as a shortcoming of Sphinx, and ideally Sphinx would be capable of adding domain nodes to the toctree itself. I've started work on this in [sphinx-doc/sphinx#6316](https://github.com/sphinx-doc/sphinx/issues/6316), but it might take a while.

I completely agree, and the interface you suggest there seems nice to me. Though, I don't know much about the toctree part of Sphinx, so I can't say what the best implementation strategy is.

**Comment by AWhetter** [comment]
Sphinx is now capable of adding domain objects to the toctree itself. Therefore add_domain_to_toctree was removed from AutoAPI and this issue is no longer relevant.
