### ISSUE TITLE
Including function source in the generated documentation?

### ISSUE THREAD

**Issue by SamWilsn** [readthedocs/sphinx-autoapi#291]
With viewcode, I can _link_ to the source for a function, but I'd like to include the source for a function immediately in the documentation (preferably without the docstring.) Is that something I can do with `autoapi`, or possibly with other sphinx extensions?

**Comment by SamWilsn** [comment]
I've hacked this together for the time being, but I still need to figure out a way to exclude docstrings.

```
{% set suffix = 1 + obj.obj.name|length %}
{% set module_name = obj.obj.full_name[:-suffix] %}
{% set module = obj.app.env.autoapi_objects[module_name] %}

.. literalinclude:: ../../../../src/{{ module.obj.relative_path }}
   :language: {{ module.language }}
   :lines: {{ obj.obj.from_line_no }}-{{ obj.obj.to_line_no }}
```

**Comment by AWhetter** [comment]
We don't store the source code of a parsed item in any AutoAPI objects and doing so would be too slow and wasteful. If you want this behaviour, it would need to be implemented in viewcode itself.

**Comment by SamWilsn** [comment]
You might not store the source, but you do store the line numbers and path. I don't think providing a new directive that uses that information and injects the source code would be too difficult. Could even be a subclass of `literalinclude`.

---

Just in case anyone else stumbles across this issue, I hacked together a quick sphinx plugin to exclude docstrings: https://pypi.org/project/undocinclude/
