### ISSUE TITLE
`source_suffix` fallback doesn't allow `dict`

### ISSUE THREAD

**Issue by mgeier** [readthedocs/sphinx-autoapi#294]
This assumes that `source_suffix` is a `list`:

https://github.com/readthedocs/sphinx-autoapi/blob/613eff53a7801d94eb864f2e27924d7d5592556f/autoapi/extension.py#L162

Quite a long time ago, Sphinx added support for using a `dict` instead, and now this is the recommended usage, see https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-source_suffix.

**Comment by ain-soph** [comment]
So maybe a quick fix would be `list(source_suffix)[0]` ?  
Or do any pre-checks to ensure the it won't be empty?

**Comment by ain-soph** [comment]
Yes. It seems the repo authors don't take the case into consideration where `".rst" not in source_suffix.keys()`.

**Comment by AWhetter** [comment]
This was already closed in #321. Proper markdown support will be added in #287
