### ISSUE TITLE
Template Questions

### ISSUE THREAD

**Issue by freddyaboulton** [readthedocs/sphinx-autoapi#295]
Hello!

I recently got autoapi to build the documentation for my project (saves us 3 minutes compared to autodoc!) but the documentation doesn't look the same.

How can I use different templates to control how different modules and classes look? The documentation says "Every type of data structure has its own template" but I'm not quite sure how I can leverage that.

Apologies for the vague question but I'd like to learn as much about templating as possible. If I can't get the docs to look the same, I think we'll have to stick with autodoc.

Thanks!

**Comment by AWhetter** [comment]
The documentation describes this process here: https://sphinx-autoapi.readthedocs.io/en/latest/how_to.html#how-to-customise-layout-through-templates
Please let me know if this doesn't answer you questions you have.

**Comment by freddyaboulton** [comment]
Thanks for getting back to me @AWhetter ! Is there a way to specify a template for a specific class in my package? With `auto_summary` we can do:

```
Transformers
~~~~~~~~~~~~
Transformers are components that take in data as input and output transformed data.

.. autosummary::
    :toctree: generated
    :template: transformer_class.rst
    :nosignatures:

    DropColumns
    SelectColumns
    OneHotEncoder
    TargetEncoder
    PerColumnImputer
```

Similarly, can I do the same for the template for a specific module?

The docs say I can overwrite `class.rst` and `module.rst` but that would apply for all classes and modules right?

**Comment by AWhetter** [comment]
It would but you could do something like

```rst
{% if obj.name == "MySpecialObject" %}
    .. Use my special template
{% else %}
    .. Use the regular template
{% endif %}
```
