### ISSUE TITLE
Customizing toc headers

### ISSUE THREAD

**Issue by quancore** [readthedocs/sphinx-autoapi#297]
@AWhetter I am trying to auto documenting one of my packages in a directory. There is one root module called `packages` and there are several directories which each of which includes a package that I am trying to document with the same name called `anofox` (same package name in different dirs with different contents). Here is the dir structure:
![image](https://user-images.githubusercontent.com/15036825/125696779-de895445-72cc-4396-a126-ab07d62dfef4.png)

For now, I tried to start documenting only `component_default`. Here is my settings for this extension in `conf.py`
```python
# Autoapi configs
autoapi_dirs = ['../../packages/']
autodoc_typehints = 'description'
autoapi_ignore = ['*migrations*', '*/proto/*',
                  '*run*', '*docker*', '*_test.py',
                  '*_test_*', '*setup*']
autoapi_ignore += ['*base_image*', '*component_common*', '*component_r*', '*component_ui*',
                   '*log_and_mon*', '*pipeline*', '*trampoline_aws*', '*trampoline_azure*', '*trampoline_common*',
                   '*trampoline_single_container*', '*workbench*']
# autoapi_add_toctree_entry = False
# autoapi_python_use_implicit_namespaces = True
```
### Problem
The problem here is that it does not include predicated ordinary directory like `component_default` or `component_ui` and starting to create TOC from `anofox`. This is problematic for me because I have several different packages from different dirs with the same name `anofox`.

### Expected behavior
I am trying to separate `anofox` packages predicated with corresponding dir name. Injected TOC should be `API Reference` -> [`component_default.anofox`, `component_ui.anofox`, ...]

**Comment by AWhetter** [comment]
This isn't something that autoapi will support because it's not conventional at all and many other tools in the Pytohn ecosystem aren't going to support this kind of layout. It seems like `anofox` should be a namespace and the other packages should be laid out under that.
