### ISSUE TITLE
1.8.2 breaks empty classes with multiline comments

### ISSUE THREAD

**Issue by tannewt** [readthedocs/sphinx-autoapi#299]
Hi hi, thanks for the improvements to autoapi! It looks like 1.8.2 broke our doc build: https://github.com/adafruit/circuitpython/runs/3167416491

The cause looks to be this input stub:

```python
class RoleError(BluetoothError):
    """Raised when a resource is used as the mismatched role.

    For example, if a local CCCD is attempted to be set but they can
    only be set when remote."""

    ...
```

The generated rst is:

```rst
.. py:exception:: RoleError

   Bases: :py:obj:`BluetoothError`

   Raised when a resource is used as the mismatched role.

       For example, if a local CCCD is attempted to be set but they can
       only be set when remote.
   Initialize self.  See help(type(self)) for accurate signature.

   Initialize self.  See help(type(self)) for accurate signature.
```

The error is:

> /home/tannewt/repos/circuitpython/shared-bindings/_bleio/index.rst:49:Block quote ends without a blank line; unexpected unindent.

**Comment by AWhetter** [comment]
Sorry about that. I've just done a release of v1.8.3 which fixed the problem. It works against circuitpython locally for me.

**Comment by jepler** [comment]
Thank you!
