### ISSUE TITLE
how to hide full path of module in sidebar?

### ISSUE THREAD

**Issue by AgentDS** [readthedocs/sphinx-autoapi#303]
Hi developers,

assuming I have package structure like:

package
 - core
    - client.py
    - server.py
 - utils
    - util1.py
    - util2.py

And using sphinx-autoapi I got rendered html page with sidebar including API reference like

package
 - package.core
    - package.core.client
    - package.core.server
 - package.utils
    - package.utils.util1
    - package.utils.util2

How to hide the full path before the specific module? I want the API reference in sidebar to be like:

package
 - core
    - client
    - server
 - utils
    - util1
    - util2

**Comment by phausamann** [comment]
Hi @AgentDS , I ran into the same problem and was able to address this by customizing the module template. Instructions on how to customize templates can be found [here](https://sphinx-autoapi.readthedocs.io/en/latest/how_to.html#how-to-customise-layout-through-templates).

I copied the [module template](https://github.com/readthedocs/sphinx-autoapi/blob/master/autoapi/templates/python/module.rst) to my local templates folder and replaced:
```
:py:mod:`{{ obj.name }}`
=========={{ "=" * obj.name|length }}
```
with
```
{{ obj.short_name }}
{{ "=" * obj.short_name|length }}
```

**Comment by AgentDS** [comment]
> Hi @AgentDS , I ran into the same problem and was able to address this by customizing the module template. Instructions on how to customize templates can be found [here](https://sphinx-autoapi.readthedocs.io/en/latest/how_to.html#how-to-customise-layout-through-templates).
> 
> I copied the [module template](https://github.com/readthedocs/sphinx-autoapi/blob/master/autoapi/templates/python/module.rst) to my local templates folder and replaced:
> 
> ```
> :py:mod:`{{ obj.name }}`
> =========={{ "=" * obj.name|length }}
> ```
> 
> with
> 
> ```
> {{ obj.short_name }}
> {{ "=" * obj.short_name|length }}
> ```

It works! thank you very much!
