### ISSUE TITLE
Support for Sphinx 4

### ISSUE THREAD

**Issue by Vineet-Sharma29** [readthedocs/sphinx-autoapi#304]
Sphinx has released `4.2.0` version. But sphinx-autoapi still has `sphinx>=3.0` added into its config. Can we upgrade `sphinx-autoapi` to `4.x` version of `sphinx`

**Comment by AWhetter** [comment]
@ain-soph is correct and AutoAPI already works with Sphinx 4. The requirement mentioned does not affect your ability to run AutoAPI with Sphinx 4.
