### ISSUE TITLE
[bug] Incorrect order for object added to the toctree

### ISSUE THREAD

**Issue by ain-soph** [readthedocs/sphinx-autoapi#308]
## Potential Bug:  

Not quite sure if it's related to #283 

### RST file:
https://github.com/ain-soph/alpsplot/blob/main/docs/source/figure.rst

`autoclass:: alpsplot.figure.Figure` introduces a class `Figure` with many methods.  
`automodule:: alpsplot.figure` involves 2 headings (`Linestyles` and `Markers`) with some texts.  

```rst
.. _alpsplot.figure:

alpsplot.figure
==================================

.. currentmodule:: alpsplot.figure

.. autoclass:: alpsplot.figure.Figure
    :members:

.. automodule:: alpsplot.figure
   :no-members:
   :no-inherited-members:
```

### Deployment:  
https://ain-soph.github.io/alpsplot/figure.html#alpsplot.figure.Figure
![image](https://user-images.githubusercontent.com/13214530/137598765-55b758e3-45b7-4d4b-ba4d-767756d3865e.png)

### Expected Order:

* Figure
* Linestyles
* Markers  

### Actual Order:

* Linestyles
* Markers  
* Figure

### Additional Material
My `conf.py` if you think might be helpful.  
https://github.com/ain-soph/alpsplot/blob/main/docs/source/conf.py

Extension settings at 
https://github.com/ain-soph/alpsplot/blob/ae99a09f5af0d1b1044a71ce87b0c06cbdd17428/docs/source/conf.py#L52-L63

and autodoc, autoapi settings at
https://github.com/ain-soph/alpsplot/blob/ae99a09f5af0d1b1044a71ce87b0c06cbdd17428/docs/source/conf.py#L97-L104

**Comment by ain-soph** [comment]
I'm not sure if this bug is a feature of sphinx, which is related to an optional argument:

https://www.sphinx-doc.org/en/master/man/sphinx-apidoc.html#cmdoption-sphinx-apidoc-M

**Comment by ain-soph** [comment]
My guess is that method `add_domain_to_toctree` inserts the object node into wrong place.

https://github.com/readthedocs/sphinx-autoapi/blob/19d217e177d76b40318a30a7cd25195d09530551/autoapi/toctree.py#L105

**Comment by AWhetter** [comment]
This does seem to be that same problem as #283 so I'm going to close this in favour of that one.
