### ISSUE TITLE
Fails to write output "AssertionError", no explanation

### ISSUE THREAD

**Issue by CornJojk** [readthedocs/sphinx-autoapi#313]
I've got a pretty straightforward project. It simply wont build. It fails at the "writing output" stage, when writing the module-level index.  I've included my index and conf. The docstrings were written by following the template from vscode "autodoc_string" extension set to "sphinx" format, nothing else. It is a total mystery. 

I've tried every version of sphinx >=4.1.2 and every version of sphinx-autopi >= 1.70

[index.txt](https://github.com/readthedocs/sphinx-autoapi/files/7529674/index.txt)
[conf.py.txt](https://github.com/readthedocs/sphinx-autoapi/files/7529687/conf.py.txt)
[sphinx-err-o_9bgs5q.log](https://github.com/readthedocs/sphinx-autoapi/files/7529715/sphinx-err-o_9bgs5q.log)

I get one other error during the consistency check:

`C:\Users\XModuleParentFolderX\docs\autoapi\index.rst: WARNING: document isn't included in any toctree`
Oddly there is no such folder as `\docs\autoapi`. There is a `docs` folder though.

**Comment by AWhetter** [comment]
I think you need to substitute `autoapi\index.rst` for `autoapi/index.rst` in the index.rst file. It's hrd to know though without a project to reproduce the problem with.
