### ISSUE TITLE
How to get rid of package and module names in toc?

### ISSUE THREAD

**Issue by FeryET** [readthedocs/sphinx-autoapi#315]
Hello.

I have created a siderbar with `autoapi` that looks like this:

```
TOC:

API Reference
        |---- src
                |----- src.package_one
                        |------ src.package_one.module_a
                        |------ src.package_one.module_b
                |----- src.module_one
```

What I want to see is something line this:
```

API Reference
     |----- package_one
            |------ module_a
            |------ module_b
     |----- module_one
```

I want to get rid of:

1. src in the TOC altogether.
2. The package.module header formatting in TOC.

The directory is like this:
```
src
├── cli.py
├── config.py
└── utilities
    ├── argument_checks.py
    ├── __init__.py
    └── schema_checks.py
```

And the conf.py has these:
```
autoapi_type = 'python'
# because the conf path is repo/docs/source/conf.py while codes are in repo/src/
autoapi_dirs = ["../../src"] 
```

Moreover, I would like to also customize my headers, can I add any attribute to the python files to make the header names different from what `apidoc` generates?

For example, the module is named `argument_checks` and now it is generated as `src.utilities.argument_checks`, I want it to become `Argument Checks`. Is this possible?

Thanks!

**Comment by AWhetter** [comment]
Do you have `autoapi_python_use_implicit_namespaces` set? That should be the only way that you get this behaviour.

**Comment by AWhetter** [comment]
Closing due to lack of feedback but a solution to #283 may also fix this.
