### ISSUE TITLE
Items in toc tree becomes smaller in the sidebar each level going down

### ISSUE THREAD

**Issue by FeryET** [readthedocs/sphinx-autoapi#316]
Hi.

I wanted to add to my previous issue, but thought maybe creating a new one would be more helpful to others in my position searching for a solution.

I have created a directory tree of rst files using autoapi. My setting for autoapi is this in `conf.py`:

```
extensions = [
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.intersphinx",
    "sphinx.ext.githubpages",
    "sphinx.ext.intersphinx",
    "sphinxcontrib.confluencebuilder",
    "autoapi.extension",
]

# --- autoapi section
add_module_names = False
add_package_names = False
autoapi_type = "python"
autoapi_dirs = ["../../src"]
autoapi_add_toctree_entry = False
autoapi_python_use_implicit_namespaces = True
autoapi_keep_files = True
autoapi_generate_api_docs = False


# -- autosectionlabel section 
autosectionlabel_prefix_document = True
```

As you can see the toc created by this config is not readable:
![image](https://user-images.githubusercontent.com/30388648/146239857-5ce62d1a-7cc2-4308-8987-33ab6febfa27.png)

What is causing this issue?

**Comment by AWhetter** [comment]
What do you mean by it isn't readable? If it's just that the font is smaller, that an issue with the theme that you have chosen and not with AutoAPI.
