### ISSUE TITLE
Typehints derived from type comments not properly handled in generated signature and parameters

### ISSUE THREAD

**Issue by fmigneault** [readthedocs/sphinx-autoapi#318]
When type hints are generated for class methods that provide the types using the comment annotation format, some cases are not handled correctly. (i.e.: using `# type: (<args>) -> <return>`)

1. Base classes are replaced by the first argument from their corresponding `__init__` call. 
    For some reason, the `Parameters` section for the class' `__init__` are not reported anywhere. 
    (maybe because they are already processed as base class components, instead of self, so no more parameters to process?)
2. Parameters in other methods have their types offset by one. 

All this is most definitely caused by `inspect.signature` that does not include `self` or `cls` definitions, since they are not to be provided  type comments definitions (similar to how the instance reference is automatically passed during the method call and must not be passed as argument). 
Instead of `inspect.siganture`, one should use `inspect.getfullargspec` to obtain the full arguments derived from type comments, including `self` for methods or `cls` for classmethods.

Use cases are demonstrated in below images. 

using `autodoc_typehints = "description"`

![image](https://user-images.githubusercontent.com/19194484/148670381-2f8cbaed-2e74-4a94-8f1f-5c434d8ea601.png)

with `autodoc_typehints` disabled

![image](https://user-images.githubusercontent.com/19194484/148670384-02dde3ec-b3ea-4096-bc2e-14661c2ddfff.png)

corresponding code: 

![image](https://user-images.githubusercontent.com/19194484/148670398-44d4e836-3951-44a8-afd5-61cc90917ebe.png)

source code for reference: https://github.com/Ouranosinc/Magpie
and config: https://github.com/Ouranosinc/Magpie/blob/master/docs/conf.py

**Comment by mathbou** [comment]
I made a PR (#300) months ago about this problem, still waiting for review 😕

**Comment by AWhetter** [comment]
Apologies for taking so long to look at #300. That PR has now been merged so please let me know if this is still an issue.

**Comment by AWhetter** [comment]
Closing due to lack of feedback and assuming that the merged pull request fixed this issue.
