### ISSUE TITLE
consistency check warning

### ISSUE THREAD

**Issue by warsaw** [readthedocs/sphinx-autoapi#319]
If I leave `autoapi_add_toctree_entry = True` and don't explicitly add the index to my toctree, i.e.:

```
.. toctree::

    using
    NEWS
```

Then I get this warning when I generate my documentation:

`checking consistency... /Users/barry/projects/public/docs/autoapi/index.rst: WARNING: document isn't included in any toctree`

even though the autoapi index is included in the rendered documentation.  I obviously don't get this warning if I turn `autoapi_add_toctree_entry = False` and use

```
.. toctree::

    using
    NEWS
    autoapi/public/index
```

**Comment by prokie** [comment]
@AWhetter Can you release this fix?
