### ISSUE TITLE
Allow for multiple language support.

### ISSUE THREAD

**Issue by pcarinhas** [readthedocs/sphinx-autoapi#320]
We have multiple repos that work together like this

```
SuperProject
   | - PythonA
   | - PythonB
   | - GolangC
```
We need to be able to document all of these at once.

**Comment by tyleraharrison** [comment]
Agreed, this would be super useful for us

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
