### ISSUE TITLE
Can't install sphinx-autoapi with python2 because of unidecode require.

### ISSUE THREAD

**Issue by EmileLabrosse1** [readthedocs/sphinx-autoapi#326]
Hello !
My company still uses python2.7. Recently I've been trying to install sphinx-autoapi==0.7.1 through pip. However it won't let me install it for python2 as the package requires the latest version of unidecode which is not compatible with python2.  

I think the solution would be to freeze the version of unidecode in sphinx-autoapi 0.7.1 and release it as 0.7.2 so that python2 users can install the plugin.

**Comment by AWhetter** [comment]
Hey @EmileLabrosse1. This is related to https://github.com/avian2/unidecode/issues/70. If you are using an up to date version of pip then you should already be getting the correct version of unidecode. I recommend updating the version of pip that you are using. If that is not possible or does not work for whatever reason then you need to set `unidecode<1.3.0; python_version<'3'` somewhere in your dependencies.
