### ISSUE TITLE
asterisk in first position in Python function signature is dropped

### ISSUE THREAD

**Issue by dhalbert** [readthedocs/sphinx-autoapi#328]
Python 3.9.10
sphinx-autoapi: 1.8.4
Sphinx: 4.4.0
astroid: 2.9.3

The asterisk keyword indicator in a Python function argument list is being dropped in the generated documentation, if it occurs before any other arguments.

module.py:
```py
def f(*, a, b):
    """f function"""
    pass

def g(a, *, b):
    """g function"""
    pass
```
generates the HTML below. Note the missing `(*, `.

Is this an `astroid` parsing problem? Should I/you file an issue there? Thanks.

Here are all the build files:
[sigs.zip](https://github.com/readthedocs/sphinx-autoapi/files/8110711/sigs.zip)

![image](https://user-images.githubusercontent.com/2847802/154991631-167498a6-068c-455d-8fa2-b583285b5dbe.png)

**Comment by dhalbert** [comment]
I looked at the output of astroid for parsing these simple cases, and it looks OK.

**Comment by jepler** [comment]
This adds a (failing) test for the problem:
```
diff --git a/tests/test_astroid_utils.py b/tests/test_astroid_utils.py
index 823dbbb..2402f5e 100644
--- a/tests/test_astroid_utils.py
+++ b/tests/test_astroid_utils.py
@@ -181,6 +181,13 @@ class TestAstroidUtils:
                     sys.version_info[:2] < (3, 8), reason="Uses Python 3.8+ syntax"
                 ),
             ),
+            pytest.param(
+                "*, a: int, b: int",
+                "*, a: int, b: int",
+                marks=pytest.mark.skipif(
+                    sys.version_info[:2] < (3, 8), reason="Uses Python 3.8+ syntax"
+                ),
+            ),
             ("a: int, *args, b: str, **kwargs", "a: int, *args, b: str, **kwargs"),
             ("a: 'A'", "a: A"),
         ],
```

**Comment by jepler** [comment]
btw we encountered this 'in the wild': https://github.com/adafruit/circuitpython/issues/6072#issuecomment-1141976045
