### ISSUE TITLE
Python Support Function Wrappers/Decorators

### ISSUE THREAD

**Issue by APN-Pucky** [readthedocs/sphinx-autoapi#334]
Hi,
I really like autoapi for python. I think I encountered a bug/difference to autosummary. My code is

```py
@doc.append_doc(ffit.fit_kwargs)
@doc.append_str("\t")
@doc.append_str(doc.table(default, init=False))
@doc.append_str(doc.table({"plot_kwargs        ": ["default", "description"]}, bottom=False))
def plot_kwargs(kwargs):
    """Set default plot_kwargs if not set.

    """
    kwargs = ffit.fit_kwargs(kwargs)
    for k, v in default.items():
        if not k in kwargs:
            kwargs[k] = v[0]
    return kwargs
```

With autoapi I only get "Set default plot_kwargs if not set." from the docstring. 

With autosummary I get the appended doc infos too.

I guess autoapi parses the source while autosummary loads the python module.

Are there any plans to support function wrappers?
Cheers

**Comment by AWhetter** [comment]
Run time editing of a docstring like this is very difficult to simulate with static analysis. Maybe one day we'll implement some sort of plugin functionality so that you can teach autoapi what your decorators mean. There are no plans for doing this though
