### ISSUE TITLE
Attribute assignment with `.` operator only considers the attribute name

### ISSUE THREAD

**Issue by gurukamath** [readthedocs/sphinx-autoapi#341]
While assigning a value to an attribute (in a global context), the generated node name consists only of the attribute name. The object/class  name is omitted.

Consider the following example
```
from temp import A, B

A.y = 10

B.y = 5
```

The two `data` nodes generated have the same name `y` instead of `A.y` and `B.y`. Is this how it was intended to be. 

If this is not how it was intended, I can raise a PR to fix this. I believe it is better to capture the class/object name in the `data` nodes name.

**Comment by AWhetter** [comment]
Really we shouldn't document these attributes at all. At least not at the module level.
