### ISSUE TITLE
Hogging resources on M1

### ISSUE THREAD

**Issue by JeffSolo** [readthedocs/sphinx-autoapi#345]
Running on Macbook Pro M1 locks up the rest of the system.

When building with autoapi, the rest of my system becomes basically unusable:
* VSCode gives "EAGAIN" error when trying to search
* Shell background operations emit: `zsh: fork failed: resource temporarily unavailable`
* Chrome becomes unresponsive

**Comment by AWhetter** [comment]
I can't debug your issue without more information. Do you have a set of sphinx and Python files that I can test against?
