### ISSUE TITLE
Problem with `NamedTuple` inheritance

### ISSUE THREAD

**Issue by sammorley-short** [readthedocs/sphinx-autoapi#350]
When I add the following class definition to a module

```python
from typing import NamedTuple

class MyClass(NamedTuple):
    """Docs."""
```

I get the following error:

```
Extension error (autoapi.extension):
Handler <function run_autoapi at 0x111be0310> for event 'builder-inited' threw an exception (exception: dictionary changed size during iteration)
```

and when I remove these lines the error is not thrown.

I'm not sure what's causing this, but it may be related to #349, since their code also seems to be concerning named tuples.

**Comment by AWhetter** [comment]
Thanks for reporting this issue, @sammorley-short.
I can't reproduce this error. Are you still able to reproduce it yourself? If so then please can you provide a more complete reproduction case including things like source .rst files, the version of Python, the version of Sphinx, and the version of AutoAPI.
