### ISSUE TITLE
Modules not shown as headers

### ISSUE THREAD

**Issue by APN-Pucky** [readthedocs/sphinx-autoapi#360]
My doc showed Subpackages, Package Contents etc as headlines instead of the actual module names, since the first line module was not handled as header:
![2022-12-05 14_53_25-Subpackages](https://user-images.githubusercontent.com/4533248/205654201-6e1ea905-8f2d-4dac-b432-edf6cc1d64d3.png)
![2022-12-05 14_53_18-hepi](https://user-images.githubusercontent.com/4533248/205654208-8ace8b45-99a2-4216-9759-0b74c6faaf72.png)

The rst-file actually shows it as a header:
```rst
1 :py:mod:`hepi`
2 ===================
```
When I place a newline (or anything) above the first line then the header shows up properly again.

This unexpected behavior only happens only when I set `rst_prolog` in conf.py. I double checked that I place 2 newlines in the prolog command.

The issue #302 seems slightly related.

**Comment by AWhetter** [comment]
This is an issue in Sphinx, so I have submitted an issue upstream: https://github.com/sphinx-doc/sphinx/issues/11437
