### ISSUE TITLE
> If you implement it in a way that anticipates that `rtd_theme_version` may be `None` then it can work. For instance `{%- if rtd_theme_version -%}(v{{ rtd_theme_version }}){%- endif -%}`

### ISSUE THREAD

**Issue by kkhuaa** [readthedocs/sphinx-autoapi#363]
> If you implement it in a way that anticipates that `rtd_theme_version` may be `None` then it can work. For instance `{%- if rtd_theme_version -%}(v{{ rtd_theme_version }}){%- endif -%}`

The question is: How can it be `None` if I set it in:
`app.connect("html-page-context", update_context)`
?

_Originally posted by @marxin in https://github.com/readthedocs/sphinx_rtd_theme/issues/1269#issuecomment-1381545029_

**Comment by AWhetter** [comment]
I don't understand what this issue is asking for and the linked issue does not relate to AutoAPI at all.
