### ISSUE TITLE
Duplicate objects in module contents

### ISSUE THREAD

**Issue by sinus-x** [readthedocs/sphinx-autoapi#369]
**Note: This is not caused by imports.** There have been several issues caused by importing an object from another module. This is not the case.

Objects (classes, methods) are defined multiple times in module contents:

![image](https://user-images.githubusercontent.com/14353790/218281873-617cef00-4a47-4b14-a2ee-c77e2ccbbbeb.png)

I've traced down the problem to function **`autoapi/toctree.py:add_domain_to_toctree()`**; when changed to no-op the module contents only includes each object once.

Minimal working example:

<details>

**conf.py**

```py
extensions = ["sphinx.ext.autodoc", "autoapi.extension"]

templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

autoapi_dirs = ["."]

html_theme = "furo"
html_static_path = ["_static"]
```

**index.rst**

```rst
:py:mod:`foo`
=============

.. py:module:: foo

Module Contents
---------------

.. py:function:: generate() -> int

   Generate integer.

.. py:function:: request(key: str, number: int)

   Request a value.
```

```console
$ sphinx-build -M html . _build
```

</details>

This is only reproducible with Sphinx>=5.2.0. Before that, AutoAPI works as expected. It is not a problem with Furo (which is used on the screenshot); using Sphinx<=5.1.1 does not suffer from this issue.

**Comment by AWhetter** [comment]
Closed by #374
