### ISSUE TITLE
sphinxcontrib-dotnetdomain is deprecated

### ISSUE THREAD

**Issue by mreutman** [readthedocs/sphinx-autoapi#371]
Hello,

I was looking to use this project to document some .NET code. It seems to depend on `sphinxcontrib-dotnetdomain`, but that project is no longer maintained & does not appear to work with the latest release of Sphinx. Is there any way to work around this or is .NET support no longer planned?

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
