### ISSUE TITLE
Customize class rendering

### ISSUE THREAD

**Issue by le91688** [readthedocs/sphinx-autoapi#373]
Given the example:

```python
class Foo(Base):
    """Foo

    Attributes:
        bar (sometype): Bar

    """
```
It is output via AutoAPI as so:

![image](https://user-images.githubusercontent.com/8898300/227278941-65518229-5cf4-47dc-a5a4-42a85a7dc825.png)

This is not really idea for when you have a class with a large number of members, so I was trying to get the Type info  to be presented on the attribute line, the doctored image below as an example

![image](https://user-images.githubusercontent.com/8898300/227279915-9433836b-da52-48b7-a202-a35ea6926fc0.png)

Is it possible to customize this with any current configuration options? Ive poured over the docs and didnt see anything

**Comment by le91688** [comment]
to follow up:

Im guessing I can modify templates to achieve this, but ive not been able to figure out how to do this.

This seems like it is  output via attribute template, which just is `{% extends "python/data.rst" %}`, so my guess is modification to data.rst is the answer?

**Comment by AWhetter** [comment]
Yes, you would need to customise your own templates to achieve this.
The "attribute" template refers to attributes on a class, which is what you've described in this issue. The "data" template refers to module level variables. So if you're happy for the output of both of those types of variable to be customised, then you only need to modify the `data.rst` template. However if you only want the output of class level attributes to change then you'll need to copy the contents of the "data" template into an `attribute.rst` template and customise from there.
