### ISSUE TITLE
How to hide the module name of parameter type

### ISSUE THREAD

**Issue by zhiyiYo** [readthedocs/sphinx-autoapi#376]
Hi, Is there any method to hide the module name in the method signature
![image](https://user-images.githubusercontent.com/65096819/229449162-7eebcde3-736e-43fa-815f-d7ca73f4700f.png)

**Comment by AWhetter** [comment]
There is no way of doing this. If AutoAPI weren't to include the fully qualified name of the type, then Sphinx would not be able to link to the type and it would be unclear to users where the type exists.
