### ISSUE TITLE
License incompatibility caused by GPL-licensed dependency `unidecode`

### ISSUE THREAD

**Issue by gaokai320** [readthedocs/sphinx-autoapi#382]
Hello,

We are a group of researchers developing tools to monitor and remediate open-source license incompatibilities in the PyPI ecosystem.

We find that your `sphinx-autoapi` package has a **GPL-2.0-or-later** licensed dependency `unidecode`. This could be problematic because GPL-licensed software requires any of its derivative work to be also licensed under GPL, but `sphinx-autoapi` is licensed under MIT.

To remove this license incompatibility, the following possible remediations may be considered:
* Relicense `sphinx-autoapi` under a GPL-3.0
* Change the `unidecode` version to 0.04.6
* Migrate `unidecode` to `text-unidecode`
* Remove `unidecode`

Note that the above remediations are generated by an automated tool that is still under test, may be incorrect, and does not represent legal advice.

We welcome any suggestions and feedback! Thank you.

**Comment by 12rambau** [comment]
I faced to same problem recently in one of my project and ended up using `anyascii` which is MIT licensed. There were nearly nothing to change. I can make a PR if maintainers think it worth the shot.

**Comment by AWhetter** [comment]
Thanks for the recommendation @12rambau. It was easy enough to switch over to anyascii that I've done it already.
