### ISSUE TITLE
Use Github Actions and trusted publishing for releases

### ISSUE THREAD

**Issue by AWhetter** [readthedocs/sphinx-autoapi#388]
Switch from a manual release process to a more automated one: https://github.com/marketplace/actions/pypi-publish#trusted-publishing

**Comment by AWhetter** [comment]
@ericholscher Please could I be given the management permissions on sphinx-autoapi in PyPI to get this set up? Thanks!

**Comment by ericholscher** [comment]
@AWhetter Sure, I've upgraded your access 👍
