### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [readthedocs/sphinx-autoapi#402]
Is it possible next time on release new version make the github release to have entry on https://github.com/readthedocs/sphinx-autoapi/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.
My automation process those notification trying make preliminary automated upgrade of building packages which allow save some time on maintaining packaging procedures.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by 12rambau** [comment]
I don't know what is the release process of this repository but on my repositories to make sure I don't forget the GH release I actually use it as a trigger for the release github actions (that then take care of all the others: npm, pypi, rdt, conda ...)

**Comment by kloczek** [comment]
As your repo already is using GH workflows easiest would be use that https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026

**Comment by AWhetter** [comment]
I know that you had asked for a Github release for the next version, but I've had to release v3.0.0 earlier than expected due to the release of a dependency causing the current version of AutoAPI to fail. I do intend on making github releases in the future though.

**Comment by AWhetter** [comment]
I've made a release for v3.0.0. I've also updated the release process in #388 such that sdists and wheels will get automatically uploaded to the release with signatures.

Thanks for the suggestion and resources!

**Comment by kloczek** [comment]
All what I can tell is that my automation was able to process email notification and automatically upgrade package with your module. It looks like it builds correctly.
(Automated testing still is not not started yet .. because it is long queue of other packages to test)
Thank you very much 👍 😄
