### ISSUE TITLE
is it possible to split class method in separated pages ? 

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/sphinx-autoapi#403]
I have a pretty heavy API to document and it's barely readable if all class methods are stored in the same file, I'm very much interested in the work done in https://github.com/readthedocs/sphinx-autoapi/pull/399. 

Would it be possible to reach even smaller level of granularity ?

maybe special case everything is not the way to go and a custom template would be more advisable. Is templating available for autoapi ? 

I would like to split my doc like pandas is doing e.g. : https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.size.html

**Comment by AWhetter** [comment]
This will get implemented as part of #226. Thanks for the additional example of pandas!
