### ISSUE TITLE
Difference between submodules and subpackages?

### ISSUE THREAD

**Issue by dstansby** [readthedocs/sphinx-autoapi#450]
I'm trying to use `autoapi` to document a package, and am getting the API docs grouped in both "submodules" and "subpackages":

<img width="332" alt="Screenshot 2024-05-28 at 16 48 21" src="https://github.com/readthedocs/sphinx-autoapi/assets/6197628/395b1414-8f8f-4802-904b-b619a307aee6">

Does anyone know

1. The difference between a submodule and a subpackage?
2. How I can group these together (ie. merge the lists above) so that all the second level API docs are in a single list, instead of spread across submodules and subpackages

**Comment by AWhetter** [comment]
A package is a directory that contains an `__init__.py` and may have packages or modules under it. A module is a .py file. There's no difference in usage to a user however so it's maybe a bit pedantic to separate them. I think we'll change this to lump everything under "submodules".

**Comment by zbentley** [comment]
+1 to merging them; I think many packages like to move things between "submodule" and "subpackages" as an internal implementation detail (e.g. when a `submodule.py` grows so much support code for its public exports that it needs to be split into `submodule/__init__.py` for public stuff and `submodule/_internal.py` for the rest).

**Comment by zbentley** [comment]
Terrific, thanks so much @AWhetter!

**Comment by austinzh** [comment]
> A package is a directory that contains an `__init__.py` and may have packages or modules under it. A module is a .py file. There's no difference in usage to a user however so it's maybe a bit pedantic to separate them. I think we'll change this to lump everything under "submodules".

any update on this, or maybe a workaround to have only submodules?
