### ISSUE TITLE
Don't show special-members when enabling inherited-members

### ISSUE THREAD

**Issue by q-wertz** [readthedocs/sphinx-autoapi#464]
Hello,

not sure if I misunderstood something or this is related to (or the same as in) https://github.com/readthedocs/sphinx-autoapi/issues/417.

If I have the following config:
```python
autoapi_options = [
    "members",
    "inherited-members",  # disabled by default
    "undoc-members",
    # "special-members",  # disabled by default
    # "private-members",
    "show-inheritance",
    "show-inheritance-diagram",  # disabled by default
    "show-module-summary",
    "special-members",
    "imported-members",
]
```
in my `conf.py` file in my understanding there should not be any special-member displayed in the derived classes. 

It seems to work for most cases (derived from my own superclass or from `abc.ABC`), but in the documentation of enums (derived from `enum.Enum`) special members like `__repr__()`, `__str__()`, ... are displayed.

**Comment by AWhetter** [comment]
You have `special-members` included twice. It's commented out once and present again as the second to last item in the list.

**Comment by q-wertz** [comment]
OMG 🤦‍♂️
Sorry. Codeblind
