### ISSUE TITLE
Option to exclude members inherited from stdlib when 'inherited-members' is enabled

### ISSUE THREAD

**Issue by dkbarn** [readthedocs/sphinx-autoapi#467]
When the 'inherited-members' option is enabled, classes which inherit from a standard library class, such as Exception or TypedDict, will have all of the dunder methods on that class included in the documentation. For example, `__str__()`, `__delattr__()`, `__dir__()`, `__eq__()`, `__format__()`, etc etc

It would be helpful if there was a way to exclude members defined in the standard library when 'inherited-members' is enabled, since I can't think of many cases when this is useful to include.

**Comment by AWhetter** [comment]
I've taken quite an opinionated approach to this and always excluded members inherited from classes that live in the standard library, with the exception of abstract classes (eg. inheriting from something in `collections.abc` to make a collection type).
As it is now, I think that the "inherited-members" option is way too verbose, to the point of being unusable.
