### ISSUE TITLE
3.3.0 Feature to ignore stdlib APIs breaks CircuitPython

### ISSUE THREAD

**Issue by tannewt** [readthedocs/sphinx-autoapi#478]
We reimplement some of the stdlib and the change in 3.3.0 causes our docs to disappear. ReadTheDocs breaks due to a missing reference.

It is important for us to list what we implement because we don't implement everything.

Please add a way to disable this behavior.

**Comment by tannewt** [comment]
For example, our `ssl.SSLContext.wrap_socket` is no longer listed.

**Comment by tannewt** [comment]
Also note that we don't do any inheritance. We're defining modules and classes with the same names as those in the stlib. So maybe ensure that these members actually come from the inheritance.

**Comment by AWhetter** [comment]
Sorry about this. I implemented the drastic approach of doing this filtering at the parser level, but I should have done it in such a way that you could at least use the autoapi-skip-member event to override the behaviour.
I should have some time to address the problem this weekend.

**Comment by AWhetter** [comment]
I've tested v3.3.1 against CircuitPython and the docs now build. The missing members look to be present in the ssl module at least. Please let me know if you're still seeing issues.
