### ISSUE TITLE
__all__ not respected when going from 3.0.0 to 3.1.0

### ISSUE THREAD

**Issue by dstansby** [readthedocs/sphinx-autoapi#481]
Over at zarr we've noticed that bumping autoapi from 3.0.0 to 3.1.0 results in `__all__` not being respected by autoapi for some sub-modules. The same issue still persists with the latest version, 3.3.1.

An example failing build can be found at https://readthedocs.org/projects/zarr/builds/25599267/.

Sorry that's not much to go on, but I'm hoping I can bisect to work out which commit caused the issue next.

**Comment by dstansby** [comment]
Bisects to a6558dcfc225e9ec840c6436da17e5e46e2709d5 as the first bad commit

**Comment by dstansby** [comment]
As well as `__all__` not being respected, it also looks like `autoapi` is trying to document `__all__` as a module attribute - perhaps this helps diagnose the issue?

**Comment by dstansby** [comment]
AHA this problem goes away if we comment out `app.connect("autoapi-skip-member", autoapi_skip_modules)`, so it seems to be an issue with `__all__` not being respected when the `autoapi-skip-member` event is connected to.

**Comment by AWhetter** [comment]
I can't reproduce this behaviour. `__all__` will only be documented if `special-members` is turned on, which it is by default, and as was the case in the zarr code base before https://github.com/zarr-developers/zarr-python/pull/2177/files
In the case of `autoapi-skip-member`, it overrides whatever the default skip value is when you return anything other than `None`. In the zarr code base, `autoapi_skip_modules` was always returning a `bool` and therefore would override whatever the default behaviour was resulting from the usage of `__all__`.

So I don't think that there's anything to address here but let me know if you think I'm mistaken.
