### ISSUE TITLE
Asterisks in .NET XML doc comments result in RST errors

### ISSUE THREAD

**Issue by danroth27** [readthedocs/sphinx-autoapi#49]
This [method](https://github.com/aspnet/FileSystem/blob/dev/src/Microsoft.AspNet.FileProviders.Abstractions/IFileProvider.cs#L32):

``` c#
/// <summary>
/// Creates a <see cref="IChangeToken"/> for the specified <paramref name="filter"/>.
/// </summary>
/// <param name="filter">Filter string used to determine what files or folders to monitor. Example: **/*.cs, *.*, subFolder/**/*.cshtml.</param>
/// <returns>An <see cref="IChangeToken"/> that is notified when a file matching <paramref name="filter"/> is added, modified or deleted.</returns>
IChangeToken Watch(string filter);
```

Results in this error:

```
C:\Users\daroth\Documents\GitHub\apidocs\docs\autoapi\Microsoft\AspNet\FileProviders\IFileProvider\index.rst:107: WARNING: Inline emphasis start-string without end-string.
```

Here's the generated RST:

```
:param filter: Filter string used to determine what files or folders to monitor. Example: **/*.cs, *.*, subFolder/**/*.cshtml.
```

**Comment by agjohnson** [comment]
The best way to handle this is maybe by including a sphinx option for whether comments should be interpreted as rST or raw text. It's being interpreted as rST currently, though the ASP.NET docs will obviously not have any rST.

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
