### ISSUE TITLE
Broken examples?

### ISSUE THREAD

**Issue by ccoVeille** [readthedocs/sphinx-autoapi#506]
I looked a Contributions>Examples on the website and none are working.

Where can we find what your plugin could look like once installed on sphimdoc?

Can you use your own code as an example?

Maybe I have simply missed something obvious, please let me know

**Comment by AWhetter** [comment]
There isn't a "Contributions>Examples" section. There's a guide to getting started here: https://sphinx-autoapi.readthedocs.io/en/latest/tutorials.html

CircuitPython makes use of autoapi here: https://github.com/adafruit/circuitpython/blob/6232e87bdf7abed62c61f4d9f4759242d373e46f/conf.py#L100-L113
They do some customisations of the template, but their rendered documentation looks like this: https://docs.circuitpython.org/en/latest/shared-bindings/index.html

**Comment by ccoVeille** [comment]
> There isn't a \"Contributions>Examples\" section

I should have included a link

https://sphinx-autoapi.readthedocs.io/en/latest/maintenance/design.html#examples

So here, on this page none of links work
