### ISSUE TITLE
Display .NET enum values in order

### ISSUE THREAD

**Issue by danroth27** [readthedocs/sphinx-autoapi#52]
.NET enum values should be displayed in a reasonable order. Ex numerical order. Currently the order looks a bit arbitrary. See https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/Extensions/Logging/LogLevel/index.html#fields for an example.

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
