### ISSUE TITLE
Generated .NET API ref docs should include the NuGet package ID

### ISSUE THREAD

**Issue by danroth27** [readthedocs/sphinx-autoapi#61]
The generated .NET API ref docs for types should include the source NuGet package ID. The package ID is not currently available in the metadata documents generated by docfx. This ask is tracked by https://github.com/dotnet/docfx/issues/139.

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
