### ISSUE TITLE
Provide a way to convert docfx map files to intersphinx inventories

### ISSUE THREAD

**Issue by danroth27** [readthedocs/sphinx-autoapi#62]
See https://github.com/dotnet/docfx/issues/123

**Comment by agjohnson** [comment]
This seems it should be straight forward, we'll have to watch this for more information on the proposed format.

**Comment by danroth27** [comment]
I believe docfx uses a custom .rpk format. It looks like the .rpk files for the .NET Framework are published in this NuGet package: https://www.nuget.org/packages/msdn.4.5.2/0.1.0-alpha-1508031919. It looks like the .rpk format is a custom binary format, so it might actually make more sense to write a .NET tool that can do the conversion. We would need documentation though on the .inv format so we could figure out how to generate it.

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
