### ISSUE TITLE
Confusing formatting of .NET generic types

### ISSUE THREAD

**Issue by danroth27** [readthedocs/sphinx-autoapi#75]
Ported from https://github.com/aspnet/Docs/issues/1337. I fixed up the generated rst manually, so you will need to look at the commit history to see the original issue.

In the ASP.NET Core API reference, generic types are formatted in a confusing way. For example, the return type of [`ConfigurationProvider.Data`](https://docs.asp.net/projects/api/en/latest/autoapi/Microsoft/Extensions/Configuration/ConfigurationProvider/index.html#prop-Microsoft.Extensions.Configuration.ConfigurationProvider.Data) shows as:

> System.Collections.Generic.IDictionary<System.Collections.Generic.IDictionary`2>{System.String<System.String>, System.String<System.String>}

Instead, this should show just like in the code just below:

> IDictionary<string, string>

Or maybe with namespaces included:

> System.Collections.Generic.IDictionary<string, string>

**Comment by AWhetter** [comment]
Closing this now that we are dropping support for documenting languages other than Python. See #248 for more information on this decision.
